apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: final-argo-0731
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: final-argo-0731 
  name: final-argo-0731
spec:
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app.kubernetes.io/instance: final-argo-0731 
